In [11]:
import pandas as pd
PATH = "~/data/movie_after/meta/meta.parquet"
df = pd.read_parquet(PATH)

In [14]:
df

      movieCd multiMovieYn repNationCd
0    19860125            Y         NaN
1    20124722            Y         NaN
2    20190324            N         NaN
3    20190324            N           K
4    20190324            N           K
..        ...          ...         ...
118  20236146            N           F
119  20236146          NaN           F
120  20236146            N           F
121  20236146          NaN           F
122  20236533            Y         NaN

[123 rows x 3 columns]

In [15]:
movie_df = pd.read_parquet(f"/home/seominhyuk/data/movies/dailyboxoffice/dt=20240101")

In [9]:
movie_df

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,multiMovieYn,repNationCd
0,1,1,0,OLD,20203702,노량: 죽음의 바다,2023-12-20,2893509165,38.8,-686119312,-19.2,36926118105,290717,-59184,-16.9,3728850,1706,5793,NaN,NaN
1,2,2,0,OLD,20212866,서울의 봄,2023-11-22,2666429137,35.8,-649456909,-19.6,118016920547,262422,-64054,-19.6,12117201,1614,5444,NaN,NaN
2,3,3,0,OLD,20236146,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,2023-12-22,565417320,7.6,-69888800,-11.0,6071745009,58239,-6751,-10.4,626508,834,1671,NaN,NaN
3,4,4,0,OLD,20235735,아쿠아맨과 로스트 킹덤,2023-12-20,507984981,6.8,-156026099,-23.5,7967584753,49368,-14686,-22.9,772354,832,1611,NaN,NaN
4,5,5,0,OLD,20235596,트롤: 밴드 투게더,2023-12-20,273538754,3.7,-16945147,-5.8,3383181955,28988,-1952,-6.3,365927,660,981,NaN,NaN
5,6,6,1,OLD,20234673,뽀로로 극장판 슈퍼스타 대모험,2023-12-13,113680587,1.5,2278496,2.0,3046919883,11586,190,1.7,332776,335,432,NaN,NaN
6,7,7,-1,OLD,20235290,도티와 영원의 탑,2023-12-27,100024717,1.3,-13487835,-11.9,488186693,10704,-1268,-10.6,52400,357,419,NaN,NaN
7,8,8,0,OLD,20234114,괴물,2023-11-29,92381680,1.2,-3768994,-3.9,3884333955,8710,-524,-5.7,396137,187,263,NaN,NaN
8,9,9,0,OLD,20236045,"바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!",2023-12-27,53094530,0.7,-707720,-1.3,372974290,6471,67,1.0,45294,207,248,NaN,NaN
9,10,10,1,OLD,20235980,말하고 싶은 비밀,2023-12-13,38025184,0.5,-2349427,-5.8,868379725,3765,-164,-4.2,89597,95,127,NaN,NaN
10,1,1,0,OLD,20203702,노량: 죽음의 바다,2023-12-20,2893509165,40.2,-686119312,-19.2,36926118105,290717,-59184,-16.9,3728850,1706,5793,N,NaN
11,2,2,0,OLD,20212866,서울의 봄,2023-11-22,2666429137,37.0,-649456909,-19.6,118016920547,262422,-64054,-19.6,12117201,1614,5444,N,NaN
12,3,3,0,OLD,20236146,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,2023-12-22,565417320,7.8,-69888800,-11.0,6071745009,58239,-6751,-10.4,626508,834,1671,N,NaN
13,4,4,0,OLD,20235735,아쿠아맨과 로스트 킹덤,2023-12-20,507984981,7.1,-156026099,-23.5,7967584753,49368,-14686,-22.9,772354,832,1611,N,NaN
14,5,5,0,OLD,20235596,트롤: 밴드 투게더,2023-12-20,273538754,3.8,-16945147,-5.8,3383181955,28988,-1952,-6.3,365927,660,981,N,NaN
15,6,6,1,OLD,20234673,뽀로로 극장판 슈퍼스타 대모험,2023-12-13,113680587,1.6,2278496,2.0,3046919883,11586,190,1.7,332776,335,432,N,NaN
16,7,7,-1,OLD,20235290,도티와 영원의 탑,2023-12-27,100024717,1.4,-13487835,-11.9,488186693,10704,-1268,-10.6,52400,357,419,N,NaN
17,8,8,0,OLD,20235980,말하고 싶은 비밀,2023-12-13,38025184,0.5,-2349427,-5.8,868379725,3765,-164,-4.2,89597,95,127,N,NaN
18,9,9,0,OLD,20190324,3일의 휴가,2023-12-06,28109697,0.4,-5429437,-16.2,4863180386,3295,-626,-16.0,517836,132,157,N,NaN
19,10,10,0,OLD,20235098,나폴레옹,2023-12-06,4056567,0.1,-89539,-2.2,2246030517,540,-20,-3.6,225912,23,25,N,NaN
20,1,1,0,OLD,20234114,괴물,2023-11-29,92381680,37.0,-3768994,-3.9,3884333955,8710,-524,-5.7,396137,187,263,Y,NaN
21,2,2,0,OLD,20236045,"바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!",2023-12-27,53094530,21.3,-707720,-1.3,372974290,6471,67,1.0,45294,207,248,Y,NaN
22,3,3,0,OLD,20236080,류이치 사카모토: 오퍼스,2023-12-27,31686950,12.7,-15234118,-32.5,317887981,3001,-1659,-35.6,34196,200,270,Y,NaN
23,4,4,0,OLD,20233299,크레센도,2023-12-20,29203100,11.7,-2644200,-8.3,424298400,2534,-235,-8.5,39445,79,102,Y,NaN
24,5,5,0,OLD,20235923,사랑은 낙엽을 타고,2023-12-20,11011634,4.4,285955,2.7,163391820,1052,-28,-2.6,17008,30,33,Y,NaN
25,6,6,0,OLD,20235693,리빙: 어떤 인생,2023-12-13,6942434,2.8,-1569966,-18.4,174717087,729,-181,-19.9,18551,20,23,Y,NaN
26,7,7,5,OLD,20234664,그대들은 어떻게 살 것인가,2023-10-25,3371362,1.4,-142718,-4.1,19543638004,318,-29,-8.4,2009716,17,20,Y,NaN
27,8,8,2,OLD,20124722,피아니스트의 전설,2020-01-01,3063078,1.2,-1092200,-26.3,416989591,294,-142,-32.6,51876,23,25,Y,NaN
28,9,8,0,NEW,20236533,립세의 사계,2024-01-10,2804970,1.1,2804970,100.0,4330970,294,294,100.0,512,4,4,Y,NaN
29,10,10,4,OLD,19860125,쿼바디스,1973-01-13,589000,0.2,149000,33.9,37856982,292,72,32.7,20951,1,3,Y,NaN
30,1,1,0,OLD,20236146,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,2023-12-22,565417320,34.4,-69888800,-11.0,6071745009,58239,-6751,-10.4,626508,834,1671,NaN,F
31,2,2,0,OLD,20235735,아쿠아맨과 로스트 킹덤,2023-12-20,507984981,30.9,-156026099,-23.5,7967584753,49368,-14686,-22.9,772354,832,1611,NaN,F
32,3,3,0,OLD,20235596,트롤: 밴드 투게더,2023-12-20,273538754,16.6,-16945147,-5.8,3383181955,28988,-1952,-6.3,365927,660,981,NaN,F
33,4,4,0,OLD,20234114,괴물,2023-11-29,92381680,5.6,-3768994,-3.9,3884333955,8710,-524,-5.7,396137,187,263,NaN,F
34,5,5,0,OLD,20236045,"바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!",2023-12-27,53094530,3.2,-707720,-1.3,372974290,6471,67,1.0,45294,207,248,NaN,F
35,6,6,1,OLD,20235980,말하고 싶은 비밀,2023-12-13,38025184,2.3,-2349427,-5.8,868379725,3765,-164,-4.2,89597,95,127,NaN,F
36,7,7,-1,OLD,20236080,류이치 사카모토: 오퍼스,2023-12-27,31686950,1.9,-15234118,-32.5,317887981,3001,-1659,-35.6,34196,200,270,NaN,F
37,8,8,0,OLD,20233299,크레센도,2023-12-20,29203100,1.8,-2644200,-8.3,424298400,2534,-235,-8.5,39445,79,102,NaN,F
38,9,9,0,OLD,20235923,사랑은 낙엽을 타고,2023-12-20,11011634,0.7,285955,2.7,163391820,1052,-28,-2.6,17008,30,33,NaN,F
39,10,10,0,OLD,20235693,리빙: 어떤 인생,2023-12-13,6942434,0.4,-1569966,-18.4,174717087,729,-181,-19.9,18551,20,23,NaN,F
40,1,1,0,OLD,20203702,노량: 죽음의 바다,2023-12-20,2893509165,49.8,-686119312,-19.2,36926118105,290717,-59184,-16.9,3728850,1706,5793,NaN,K
41,2,2,0,OLD,20212866,서울의 봄,2023-11-22,2666429137,45.9,-649456909,-19.6,118016920547,262422,-64054,-19.6,12117201,1614,5444,NaN,K
42,3,3,1,OLD,20234673,뽀로로 극장판 슈퍼스타 대모험,2023-12-13,113680587,2.0,2278496,2.0,3046919883,11586,190,1.7,332776,335,432,NaN,K
43,4,4,-1,OLD,20235290,도티와 영원의 탑,2023-12-27,100024717,1.7,-13487835,-11.9,488186693,10704,-1268,-10.6,52400,357,419,NaN,K
44,5,5,0,OLD,20190324,3일의 휴가,2023-12-06,28109697,0.5,-5429437,-16.2,4863180386,3295,-626,-16.0,517836,132,157,NaN,K
45,6,6,2,OLD,20202247,싱글 인 서울,2023-11-29,1903007,0.0,-409621,-17.7,3740536035,212,-17,-7.4,399787,9,9,NaN,K
46,7,7,-1,OLD,20228560,너와 나,2023-10-25,2625839,0.0,-3233861,-55.2,330224803,192,-337,-63.7,33811,8,8,NaN,K
47,8,8,1,OLD,20235697,엔시티 네이션 : 투 더 월드 인 시네마,2023-12-06,1364000,0.0,-3168000,-69.9,554784000,69,-144,-67.6,25099,8,8,NaN,K
48,9,9,6,OLD,20232077,어른 김장하,2023-11-15,214000,0.0,-58000,-21.3,230592472,31,-8,-20.5,27603,2,2,NaN,K
49,10,10,3,OLD,20227525,교토에서 온 편지,2023-12-06,207000,0.0,-67800,-24.7,58288197,29,-19,-39.6,6717,3,3,NaN,K

In [16]:
df

      movieCd multiMovieYn repNationCd
0    19860125            Y         NaN
1    20124722            Y         NaN
2    20190324            N         NaN
3    20190324            N           K
4    20190324            N           K
..        ...          ...         ...
118  20236146            N           F
119  20236146          NaN           F
120  20236146            N           F
121  20236146          NaN           F
122  20236533            Y         NaN

[123 rows x 3 columns]